Satisfy missing linker references: `/usr/bin/ld: ../libprojectM/libprojectM.a(NativePresetFactory.cpp.o): undefined reference to symbol 'dlclose@@GLIBC_2.2.5'`