libprojectm: Fix static DL_LIBS for Qt PulseAudio
Add missing "${CMAKE_DL_LIBS}" for libprojectM_static.cmake, fixing
the projectM-pulseaudio build variant.

Steps:
mkdir build && cd build
cmake .. -DENABLE_SDL=OFF -DENABLE_SDL_UI=OFF -DENABLE_PULSEAUDIO=ON
make -j$(nproc)

Before:
[100%] Linking CXX executable projectM-pulseaudio
/usr/bin/ld: ../libprojectM/[...] undefined reference to symbol
  'dlclose@@GLIBC_2.2.5'
/usr/bin/ld: /usr/lib/gcc/[...]/libdl.so: error adding symbols: DSO
  missing from command line
collect2: error: ld returned 1 exit status

After:
* Builds and runs successfully

Future work:
Expand CMake CI build matrix to enable all non-conflicting options.